export const APPWRITE_PROJECT_ID = process.env.NEXT_PUBLIC_APPWRITE_ID;
export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID;
export const CART_COLLECTION_ID = process.env.NEXT_PUBLIC_CART_COLLECTION_ID;
export const WISHLIST_COLLECTION_ID = process.env.NEXT_PUBLIC_WISHLIST_COLLECTION_ID;
export const STATUS_COLLECTION_ID = process.env.NEXT_PUBLIC_STATUS_COLLECTION_ID;


